# Generated by Django 4.2.30 on 2026-05-31 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('load_id', models.CharField(blank=True, db_index=True, max_length=16, unique=True)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('weight', models.CharField(blank=True, default='', max_length=64)),
                ('truck_type', models.CharField(blank=True, default='', max_length=64)),
                ('budget', models.CharField(blank=True, default='', max_length=64)),
                ('pickup_when', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('en_route_pickup', 'En route to pickup'), ('at_pickup', 'At pickup'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('truck_lat', models.FloatField(blank=True, null=True)),
                ('truck_lng', models.FloatField(blank=True, null=True)),
                ('truck_heading', models.FloatField(blank=True, null=True)),
                ('truck_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_shipment_loads', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipment_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cargo_owner', 'status'], name='loads_shipm_cargo_o_c51259_idx'), models.Index(fields=['driver', 'status'], name='loads_shipm_driver__131dcb_idx')],
            },
        ),
    ]
