# Generated by Django 4.2.30 on 2026-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentload',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
